### ISSUE TITLE
instant crash

### ISSUE THREAD

**Issue by paulle** [lucasnlm/antimine-android#425] opened 2023-04-19 15:27 UTC
**Describe the bug** starting the app causes instant crash

**To Reproduce**

**What control style do you use?**
You can check which control is selected on "Controls" screen.

**Expected behavior**

**Screenshots**

**Android Version:**12

**App Version** latest

**Comment by paulle** [comment] 2023-04-19 15:29
Instant crash when starting the app.
Android 12. Xperia 5 Iii

**Comment by Quantenzitrone** [comment] 2023-04-19 17:19
probably duplicate of #422

**Comment by paulle** [comment] 2023-04-19 17:20
It seems so

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 19. Apr. 2023, 19:19, schrieb Quantenzitrone :

**Closed** 2023-04-21 21:46 UTC
Labels: bug
